---
# HorizontalPodAutoscaler for GridOS
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gridos-hpa
  labels:
    app: gridos
spec:
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: gridos
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 min before scaling down
      policies:
      - type: Percent
        value: 50  # Scale down max 50% of pods at a time
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0  # Scale up immediately
      policies:
      - type: Percent
        value: 100  # Can double pods
        periodSeconds: 60
      - type: Pods
        value: 2  # Or add 2 pods
        periodSeconds: 60
      selectPolicy: Max  # Use whichever scales faster

---
# PodDisruptionBudget - ensure availability during disruptions
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gridos-pdb
  labels:
    app: gridos
spec:
  minAvailable: 2  # At least 2 pods must be available
  selector:
    matchLabels:
      app: gridos
